Template/Template/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Template.Models;

namespace Template.Controllers
{
    public class DepartmentsController : Controller
    {
       
        private readonly IWebHostEnvironment webHostEnvironment;


       
        public DepartmentsController( IWebHostEnvironment hostEnvironment)
        {
           
            webHostEnvironment = hostEnvironment;
        }

        string Baseurl = "http://localhost:50635/";
        // GET: Departments with or without search
        public async Task<IActionResult> Index(string search)
        {

            SessionStore DepInfo = new SessionStore();
            List<Department> depList = new List<Department>();
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync("api/Departments");

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var DepResponse = Res.Content.ReadAsStringAsync().Result;
                    //var myJObject = JObject.Parse(DepResponse).Last.ToList();

                    //Deserializing the response recieved from web api and storing into the Depaartment list  
                    DepInfo = JsonConvert.DeserializeObject<SessionStore>(DepResponse);

                    depList = DepInfo.data.ToList();
                    
                }
                //returning the dep list to view  
                return View(depList);
            }
           
        }

        // GET: Departments/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var department = await _context.Departments
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (department == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(department);
        //}

        //GET: Departments/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create(Departments departments)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var fileName = String.Empty;

        //        string departmentlogo = String.Empty;

        //        // Save department logo to uploads folder
        //        if (departments.Logo != null)
        //        {
        //            fileName = Guid.NewGuid().ToString() + "_" + departments.Logo.FileName;
        //            var path = "/Content/upload/departmentLogo";
        //            var uploadDir = Path.Combine(webHostEnvironment.WebRootPath, @".." + path);
        //            var imageUrl = Path.Combine(uploadDir, fileName);
        //            using (var fileStream = new FileStream(imageUrl, FileMode.Create))
        //            {
        //                departments.Logo.CopyTo(fileStream);
        //            }
        //            departmentlogo = path + '/' + fileName;
        //        }

        //        var department = new Department
        //        {
        //            NameAR = departments.NameAR,
        //            NameEN = departments.NameEN,
        //            Logo = departmentlogo
        //        };

        //        _context.Add(department);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(departments);
        //}


        // GET: Department Details on partial view
        public async Task<IActionResult> partialDepartmentDetails(int id)
        {
            using (var client = new HttpClient())


            {

                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(string.Format("api/GetDepartment/id={0}",id));
                //if (id == 0)
                //{
                //    id = _context.Departments.OrderBy(a => a.Id).First().Id;
                //}
                //var department = _context.Departments.FindAsync(id);
                //return PartialView(await department);
            }
            return PartialView();
        }

        // GET: Departments/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var department = await _context.Departments.FindAsync(id);
        //    if (department == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(department);
        //}

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,NameAR,NameEN,Logo")] Department department)
        //{
        //    if (id != department.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(department);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!DepartmentExists(department.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(department);
        //}

        // GET: Departments/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var department = await _context.Departments
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (department == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(department);
        //}

        // POST: Departments/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var department = await _context.Departments.FindAsync(id);
        //    _context.Departments.Remove(department);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool DepartmentExists(int id)
        //{
        //    return _context.Departments.Any(e => e.Id == id);
        //}
    }
}

Template/Template/Views/Departments/Create.cshtml
@model Template.Models.Departments

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameAR" class="control-label"></label>
                <input asp-for="NameAR" class="form-control" />
                <span asp-validation-for="NameAR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameEN" class="control-label"></label>
                <input asp-for="NameEN" class="form-control" />
                <span asp-validation-for="NameEN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" type="file"/>
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Template/Template/Views/Departments/Delete.cshtml
@model Template.Models.Department

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameAR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameAR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameEN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameEN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Template/Template/Views/Departments/Details.cshtml
@model Template.Models.Department

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameAR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameAR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameEN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameEN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Template/Template/Views/Departments/Edit.cshtml
@model Template.Models.Department

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Department</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NameAR" class="control-label"></label>
                <input asp-for="NameAR" class="form-control" />
                <span asp-validation-for="NameAR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NameEN" class="control-label"></label>
                <input asp-for="NameEN" class="form-control" />
                <span asp-validation-for="NameEN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Template/Template/Views/Departments/Index.cshtml
@model IEnumerable<Template.Models.Department>

@{
    ViewData["Title"] = "Index";
}


<div class="create_btn"><a asp-action="Create">Create Department</a></div>
<div class="row">
    <div class="col-md-8">
        <div id="partialDepartmentDetails"></div>
    </div>
    <div class="col-md-4">
        <div class="dapartment_list">
            <h4>Departments</h4>
            <form asp-controller="Departments" asp-action="Index">
                <input type="text" name="search">
                <input type="submit" value="search" />
            </form>
            <ul>
                @foreach (var item in Model)
                {
                    <li onclick="generate(@item.Id)"><a href="javascript:void(0)">@Html.DisplayFor(modelItem => item.NameEN)</a></li>
                }
            </ul>
        </div>

    </div>
</div>


<!--Script start-->
<script type="text/javascript">

    function generate(id) {
        if (id >= 0) {
            $.ajax({
                type: "Get",
                url: '@Url.Action("partialDepartmentDetails","Departments")',
                data: { id: JSON.stringify(id) },
                dataType: "JSON",
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    $("#partialDepartmentDetails").html("");
                    $("#partialDepartmentDetails").html(data.responseText);
                },
                error: function (data) {
                    $("#partialDepartmentDetails").html("");
                    $("#partialDepartmentDetails").html(data.responseText);
                }
            });
        }
    }

</script>
<!--Script End-->

Template/Template/Views/Departments/partialDepartmentDetails.cshtml
@model Template.Models.Department

@{
    ViewData["Title"] = "Index";
}

<div class="name_logo">
    <div class="row">
        <div class="col-md-8">
            <div class="nm_fields">
                <div class="form-group">
                    <label> <input type="text" value="@Html.DisplayFor(modelItem => Model.NameAR)" disabled> Name AR</label>
                </div>
                <div class="form-group">
                    <label> <input type="text" value="@Html.DisplayFor(modelItem => Model.NameEN)" disabled> Name EN</label>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="nm_logo"><img src="@Html.DisplayFor(modelItem => Model.Logo)"></div>
        </div>
    </div>
</div>
<nav>
    <div class="nav nav-tabs h_list" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-DepSetting-tab" data-toggle="tab" href="#nav-DepSetting" role="tab" aria-controls="nav-DepSetting" aria-selected="true">Department Settings</a>
        <a class="nav-item nav-link" id="nav-Validity-tab" data-toggle="tab" href="#nav-Validity" role="tab" aria-controls="nav-Validity" aria-selected="false">Validity</a>
        <a class="nav-item nav-link" id="nav-Users-tab" data-toggle="tab" href="#nav-Users" role="tab" aria-controls="nav-Users" aria-selected="false">Users</a>
        <a class="nav-item nav-link" id="nav-Courses-tab" data-toggle="tab" href="#nav-Courses" role="tab" aria-controls="nav-Courses" aria-selected="false">Courses</a>
        <a class="nav-item nav-link" id="nav-Events-tab" data-toggle="tab" href="#nav-Events" role="tab" aria-controls="nav-Events" aria-selected="false">Events</a>
    </div>
</nav>
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-DepSetting" role="tabpanel" aria-labelledby="nav-DepSetting-tab">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </div>
    <div class="tab-pane fade" id="nav-Validity" role="tabpanel" aria-labelledby="nav-Validity-tab">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </div>
    <div class="tab-pane fade" id="nav-Users" role="tabpanel" aria-labelledby="nav-Users-tab">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </div>
    <div class="tab-pane fade" id="nav-Courses" role="tabpanel" aria-labelledby="nav-Courses-tab">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </div>
    <div class="tab-pane fade" id="nav-Events" role="tabpanel" aria-labelledby="nav-Events-tab">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </div>
</div>
@*<div class="h_list">
        <a href="#">Department Settings</a><a href="#">Validity</a><a href="#">Users</a><a href="#">Courses</a><a href="#">Events</a>
    </div>
    <div class="nm_textarea">
        <div class="form-group">
            <textarea></textarea>
        </div>
    </div>*@